### ISSUE TITLE
got some problems to get it to work..

### ISSUE THREAD

**Issue by n1ete** [RollingStar/dial-beets#1]
I tried yesterday in a lxc container but didnt manage to get it to work...
Gave it a try on my Win machine today and got the same error.
i guess its a copy paste error? 

replaced already every tab with spaces

```
configuration error: file C:\Users\n1ete\AppData\Roaming\beets\config.yaml could not be read: while scanning a simple key
  in "C:\Users\n1ete\AppData\Roaming\beets\config.yaml", line 306, column 1
could not find expected ':'
  in "C:\Users\n1ete\AppData\Roaming\beets\config.yaml", line 307, column 1
```

thanks for advice ;)

**Comment by RollingStar** [comment]
I pushed a new version. Does it help? The [readme](https://github.com/RollingStar/dial-beets#installation) now has details on my machine.

**Comment by n1ete** [comment]
a bit late, but yeah it seems like its solved ;)

thanks a lot!

**Comment by RollingStar** [comment]
I'm glad it works!
